version: '3'
services: 
  db:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes: 
      - ./backend:/backend
    ports: 
      - 3000:3000
  frontend:
    image: nginx:1.13
    volumes: 
      - ./frontend:/usr/share/nginx/html/
    ports: 
      - 8001:80
    