version: '3.5'
services:
  app:
    build: .
    container_name: app_laravel
    ports:
      - 8001:80
    volumes:
      - ./app-laravel:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - back-end
    restart: on-failure    
networks:
    back-end:
      driver: bridge
